---
title: "Multinomial classification with tidymodels and volcano eruptions"
author: "Daniel L."
date: "6/2/2021"
output: html_document
---

https://juliasilge.com/blog/multinomial-volcano-eruptions/

```{r setup, include=FALSE}
library(knitr)
knitr::opts_chunk$set(echo = TRUE, cache = TRUE, warning = FALSE, message = FALSE, dpi = 180, fig.width = 8, fig.height = 5)
```

```{r}
library(tidyverse)
```

Let's build a multiclass random forest clasifier to predict the type of volcano based on other volcano characteristics like latitude, longitude, tectonic setting, etc. 

```{r}
volcano_raw <- readr::read_csv('https://raw.githubusercontent.com/rfordatascience/tidytuesday/master/data/2020/2020-05-12/volcano.csv')
volcano_raw %>% count(primary_volcano_type, sort = TRUE)
```
```{r}
volcano_df <- volcano_raw %>% transmute(volcano_type = case_when(str_detect(primary_volcano_type,
                                                              "Stratovolcano")~"Stratovolcano",
                                                   str_detect(primary_volcano_type, "Shield")~"Shield",
                                                   TRUE ~ "Other"),
                          volcano_number, latitude, longitude, elevation, tectonic_settings, major_rock_1) %>% 
  mutate_if(is.character, factor)
```

```{r}
library(maps)
world <- map_data("world")

ggplot() + 
  geom_map(data = world, map = world, aes(x = long, y = lat, map_id = region), color = "white", fill = "gray50", alpha = 0.2) +
  geom_point(data = volcano_df, aes(longitude, latitude, color = volcano_type), alpha = 0.8)
```

## Build a model

```{r}
library(tidymodels)
volcano_boot <- bootstraps(volcano_df)
volcano_boot 
```

```{r, error= FALSE, message = FALSE}
library(themis)
```

```{r}
volcano_recipe <- recipe(volcano_type ~ ., data = volcano_df) %>% 
  update_role(volcano_number, new_role = "Id") %>% 
  step_other(tectonic_settings) %>% 
  step_other(major_rock_1) %>% 
  step_dummy(tectonic_settings, major_rock_1) %>% 
  step_zv(all_predictors()) %>% 
  step_normalize(all_predictors()) %>% 
  step_smote(volcano_type)
```

```{r}
volcano_prep <- prep(volcano_recipe)
```

```{r}
juice(volcano_prep) %>% count(volcano_type)
```

```{r}
rf_spec <- rand_forest(trees = 1000) %>%
  set_mode("classification") %>% 
  set_engine("ranger")
rf_spec
```

```{r}
volcano_wf <- workflow() %>% add_recipe(volcano_recipe) %>% 
  add_model(rf_spec)

volcano_wf
```
```{r, echo = FALSE}
volcano_res <- fit_resamples(
  volcano_wf,
  resamples = volcano_boot,
  control = control_resamples(save_pred = TRUE,
                              verbose = TRUE)
)
```

```{r, echo=FALSE}
volcano_res
```

## Explore Results

```{r}
volcano_res %>% collect_metrics() 
```

```{r}
volcano_res %>% collect_predictions() %>% conf_mat(volcano_type, .pred_class)
```

```{r}
volcano_res %>% collect_predictions() %>% ppv(volcano_type, .pred_class)
```

```{r}
volcano_res %>% collect_predictions() %>% group_by(id) %>% ppv(volcano_type, .pred_class) %>% ggplot(aes(.estimate)) + geom_histogram(bins = 100)
```

```{r}
library(vip)
```

```{r}
rf_spec %>%
  set_engine("ranger", importance = "permutation") %>%
  fit(
    volcano_type ~ .,
    data = juice(volcano_prep) %>%
      select(-volcano_number) %>%
      janitor::clean_names()
  ) %>%
  vip(geom = "point")
```


```{r}
volcano_res %>% collect_predictions() %>% mutate(correct = volcano_type == .pred_class) %>% count(correct)
```

```{r}
volcano_pred <- volcano_res %>%
  collect_predictions() %>%
  mutate(correct = volcano_type == .pred_class) %>%
  left_join(volcano_df %>%
    mutate(.row = row_number()))

volcano_pred
```


```{r}
ggplot() +
  geom_map(
    data = world, map = world,
    aes(long, lat, map_id = region),
    color = "white", fill = "gray50", size = 0.05, alpha = 0.5
  ) +
  stat_summary_hex(
    data = volcano_pred,
    aes(longitude, latitude, z = as.integer(correct)),
    fun = "mean",
    alpha = 0.7, bins = 50
  ) +
  scale_fill_gradient(high = "cyan3", labels = scales::percent) +
  labs(x = NULL, y = NULL, fill = "Percent classified\ncorrectly")
```



